
var products = [
{
 name : "Crank shirt",
 ImgLink : "images/new/dressshirt/dressshirt.png",
 ImgAlt : "",
 description : "Long-sleeved shirt using COOL DOTS® (Cool Dots), a functional material that has ventilation holes in the crank shirt / COOL DOTS® material, and achieves excellent breathability and light weight.",
 description2 : "・ It is hard to be wrinkles by superior stretch and feels comfortable to wear. -Front plate is a snap button specification. ・ We arrange reflector print and ventilation hole on both sides. ・ We arrange high capacity pocket of zip-type on the left chest and both sides. -Equipped with an earphone pocket at the entrance of the chest pocket. ・ Cuffs omit cufflinks, and take off and wear quickly. · 19 SS is one size larger, finish the hem straight, a rough impression.",
 material : "Surface: COOL DOTS ® x Print (100% polyester)",
 measurements : "SMALL / Length: 67.5cm Width: 57.5cm Length: 83.5cm MEDIUM / Length: 69.5cm Width: 59.5cm Length: 86cm LARGE / Length: 71.5cm Width: 61.5 cm Length : 88.5 cm EXTRA LARGE / Length: 73.5 cm Width: 63.5 cm Length: 91 cm",
 productId : "CrankShirt",
 Img1 : "images/new/dressshirt/dressshirt2.png",
 Img1Alt : "",
 Img2 : "images/new/dressshirt/dressshirt3.png",
 Img2Alt : "",
 Img3 : "images/new/dressshirt/dressshirt4.png",
 Img3Alt : "",
 Img4 : "images/new/dressshirt/dressshirt5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "shirt",
 price : 80,
},
{
 name : "Convex parka",
 ImgLink : "images/new/grayhoodiezips/grayhoodiezips.png",
 ImgAlt : "",
 description : "Convex parka / 3D A pullover parka using a uniquely developed knit fabric '3D urake (Sliedee Urake)' with a unique embossing process. ",
 description2 : "-Large-capacity zip pocket on the abdomen. -The inside of the pocket is divided into three parts, according to the application, can organize your belongings. 　Demonstrates excellent storage capacity and functionality during action. ・ We arrange triangle hole which served as ventilation on the back and the neck of the hood. -The hood is a drawcord specification. -A feeling of comfortable material to the skin with a good hardness and surface irregularities. ",
 material : "Outer material: Embossed ball knit (91% polyester, 9% polyurethane) ",
 measurements : "SMALL / Length: 66 cm Width: 59 cm Length: 83 cm MEDIUM / Length: 68 cm Width: 61 cm Length: 85.5 cm LARGE / Length: 70 cm Width: 63 cm : 88 cm EXTRA LARGE / Length: 72 cm Width: 65 cm Length: 90.5 cm ",
 productId : "convexParka",
 Img1 : "images/new/grayhoodiezips/grayhoodiezips2.png",
 Img1Alt : "",
 Img2 : "images/new/grayhoodiezips/grayhoodiezips3.png",
 Img2Alt : "",
 Img3 : "images/new/grayhoodiezips/grayhoodiezips4.png",
 Img3Alt : "",
 Img4 : "images/new/grayhoodiezips/grayhoodiezips5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "outer",
 price : 140,
},
{
 name : "Crank pants",
 ImgLink : "images/new/graypants/graypants.png",
 ImgAlt : "",
 description : "Crank pants / EPIC x 3D urake Super water repellent material 'EPIC (Epic)' on the outer surface, a uniquely developed knit fabric '3D urake (Surideeurake)' with a unique embossed on the lining . ",
 description2 : "・ The waist is a drawcord specification. -Logo reflector printed on the back of the hem. -The functional fiber 'Thunderon (Saunderon)' with very high conductivity and corona discharge property is 　sewn in the inside stitch, and the occurrence of static electricity caused by friction is suppressed. ",
 material : "Outer material: EPICNY 20d 2-way stretch ripstop (100% nylon) Lining: embossed cardboard knit (polyester 91%, polyurethane 9%) ",
 measurements : "SMALL / Waist: 71-77 cm Inseam: 70 cm Width: 32.5 cm Hem Width: 17 cm MEDIUM / Waist: 75-81cm Inseam: 72cm Width: 33.5cm Hem Width: 17cm LARGE / Waist : 79-85cm Inseam: 75cm Thigh Width: 35cm Hem Width: 17.5cm EXTRA LARGE / Waist: 83-89cm Inseam: 78cm Tension Width: 36cm Hem Width: 17.5cm ",
 productId : "crankPants",
 Img1 : "images/new/graypants/graypants2.png",
 Img1Alt : "",
 Img2 : "images/new/graypants/graypants3.png",
 Img2Alt : "",
 Img3 : "images/new/graypants/graypants4.png",
 Img3Alt : "",
 Img4 : "images/new/graypants/graypants5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "pant",
 price : 110,
},
{
 name : "Notch hanten",
 ImgLink : "images/new/kimono19/kimono.png",
 ImgAlt : "",
 description : "notch hanten / KEVLAR x α A cotton-filled jacket designed based on the traditional Japanese winter clothing “ Hanban ”. ",
 description2 : "・　Insulation with superior breathability and heat retention function, the fabric made of POLARTECs 'Alpha (Alpha)', with 　aramid fiber 'KEVKAR (Kevlar)', which is resistant to tearing and abrasion on the outer layer, DYNAMONUS ( Dynamonas) is adopted. -The hook is a hook design, and both sides have a zipper pocket that doubles as a hand warmer. Not only outerwear, but also layered as middle innerwear. -The functional fiber 'Thunderon (Saunderon)' with very high conductivity and corona discharge property is 　sewn in the inside stitch, and the occurrence of static electricity caused by friction is suppressed. Surface: Dynamonas ",
 material : "2-way stretch taffeta (89% polyester, 6% aramid, 5% polyurethane) lining: Tricot mesh (100% polyester) in cotton: POLARTEC Alpha high pile insulation (100% polyester) ",
 measurements : "SMALL / Length: 64 cm Width : 61 cm Shoulder width: 62 cm Shoulder length: 64 cm MEDIUM / Length: 66 cm Shoulder width: 63.5 cm Shoulder length: 66.5 cm LARGE / Length: 68 cm Width: 65 cm Shoulder width: 65 cm Shoulder length: 69 cm EXTRA LARGE / Length: 70 cm Width: 67 cm Shoulder width: 66.5 cm 裄 length: 71.5 cm",
 productId : "notchHanten",
 Img1 : "images/new/kimono19/kimono2.png",
 Img1Alt : "",
 Img2 : "images/new/kimono19/kimono3.png",
 Img2Alt : "",
 Img3 : "images/new/kimono19/kimono4.png",
 Img3Alt : "",
 Img4 : "images/new/kimono19/kimono5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "outer",
 price : 120,
},
{
 name : "Crank coat",
 ImgLink : "images/new/navyjacket/navyjacket.png",
 ImgAlt : "",
 description : "crank coat / KEVLAR x α excellent breathability, Insulation with a heat insulation function, batting the 'Alpha (alpha)' of POLARTEC, Inc., a tear in the outer material, strong aramid fiber 'KEVKAR (Kevlar -)' to wear a woven The overcoat which adopted the cloth 'DYNAMONUS (Dynamonas)'. ",
 description2 : "-A hidden pocket is mounted on the characteristic front plate of the crank type. -Zip pocket that doubles as a hand warmer on both sides. -The functional fiber 'Thunderon (Saunderon)' with very high conductivity and corona discharge property is sewn in the inside stitch, and the occurrence of static electricity caused by friction is suppressed. Surface: Dynamonas ",
 material : "2-way stretch taffeta (89% polyester, 6% aramid, 5% polyurethane) lining: Tricot mesh (100% polyester) in cotton: POLARTEC Alpha high pile insulation (100% polyester) ",
 measurements : "SMALL / Length: 93 cm Width : 64 cm Shoulder width: 54.5 cm Length : 87.5 cm MEDIUM / Length: 95 cm Width: 56 cm Shoulder length: 90 cm LARGE / Length: 97 cm Width: 68 cm Shoulder width: 57.5 cm Length: 92.5 cm EXTRA LARGE / Length: 99 cm Width : 70 cm Shoulder width: 59 cm Sleeve length: 95 cm ",
 productId : "crankCoat",
 Img1 : "images/new/navyjacket/navyjacket2.png",
 Img1Alt : "",
 Img2 : "images/new/navyjacket/navyjacket3.png",
 Img2Alt : "",
 Img3 : "images/new/navyjacket/navyjacket4.png",
 Img3Alt : "",
 Img4 : "images/new/navyjacket/navyjacket5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "outer",
 price : 180,
},
{
 name : "Crank samue pants ",
 ImgLink : "images/new/navypantsbaggy/navybaggy.png",
 ImgAlt : "",
 description : "Crank samue pants / KEVLAR Wide pants with DYNAMONUS® (Dynamonas), a fabric made up of tear-off and abrasion-resistant aramid fibers 'KEVLAR (Kevlar)'. ",
 description2 : "-West and Suseo drawcord specifications. -Design based on the work clothes, which are everyday work clothes worn by Japanese monks. -The functional fiber 'Thunderon (Saunderon)' with very high conductivity and corona discharge property is sewn in the inside stitch, and the occurrence of static electricity caused by friction is suppressed.",
 material : "Outer material: Dynamonas 2-way stretch taffeta (89% polyester, 6% aramid, 5% polyurethane) ",
 measurements : "SMALL / Waist: 71-77 cm Inseam: 62 cm Width: 41 cm Bottom width: 27.5 cm MEDIUM / Waist: 75-81 cm Inseam : 64 cm Width: 42 cm Hem Width: 27.5 cm LARGE / Waist: 79-85 cm Inseam: 67 cm War Width: 43.5 cm Hem Width: 28 cm EXTRA LARGE / Waist: 83-89 cm Inseam: 70 cm Wary Width: 44.5 cm Hem Width: 28 cm ",
 productId : "crankSamue",
 Img1 : "images/new/navypantsbaggy/navybaggy2.png",
 Img1Alt : "",
 Img2 : "images/new/navypantsbaggy/navybaggy3.png",
 Img2Alt : "",
 Img3 : "images/new/navypantsbaggy/navybaggy4.png",
 Img3Alt : "",
 Img4 : "images/new/navypantsbaggy/navybaggy5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "pant",
 price : 100,
},
{
 name : "Zap jacket",
 ImgLink : "images/new/nylonjacket/nylonjacket.png",
 ImgAlt : "",
 description : "zap jacket / karu stretch A lapel jacket using a lightweight, durable, water-repellent stretch material 'karu stretch (cal stretch)' with a texture originally developed . ",
 description2 : "・ One button, center vent specification. ・ We arrange ventilation hole by laser punching on both sides. ・ Place a unique hanger hook hole at the back of the neck. -The functional fiber 'Thunderon® (Saunderon)' with very high conductivity and corona discharge property is sewn in the inner stitch, and the generation of static electricity caused by friction is suppressed. ・ We develop wearable pants (PO 852 PA 59) by setup. ",
 material : "Surface: nylon Taslan 2-way stretch taffeta (91% nylon, 9% polyurethane) ",
 measurements : "SMALL / Length: 74 cm Width: 57 cm Shoulder width: 44.5 cm Length: 83.5 cm MEDIUM / Length: 76 cm Width: 59 cm Shoulder width: 46 cm Length: 86 cm Length: 88.5 cm EXTRA LARGE / Length: 80 cm Width: 63 cm Shoulder width: 49 cm Length: 91 cm ",
 productId : "zapJacket",
 Img1 : "images/new/nylonjacket/nylonjacket2.png",
 Img1Alt : "",
 Img2 : "images/new/nylonjacket/nylonjacket3.png",
 Img2Alt : "",
 Img3 : "images/new/nylonjacket/nylonjacket4.png",
 Img3Alt : "",
 Img4 : "images/new/nylonjacket/nylonjacket5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "outer",
 price : 120,
},
{
 name : "Dome cap SHORT",
 ImgLink : "images/new/ridgehat/ridgehat.png",
 ImgAlt : "",
 description : "dome cap SHORT / karu stretch A cap that uses a lightweight, durable water-repellent stretch material 'karu stretch (cal stretch)' with a texture originally developed . ",
 description2 : "-A unique shape based on the hood of the dome coat's bellows. ・ Ventilation holes are placed everywhere. ・ Short brim. -Lightweight and stretchable adjuster. ・ It is a design which is difficult to lose shape even when carrying it compactly. ",
 material : "Outer material: Nylon Taslan 2-way stretch taffeta (91% nylon, 9% polyurethane)",
 measurements : "",
 productId : "domeCap",
 Img1 : "images/new/ridgehat/ridgehat2.png",
 Img1Alt : "",
 Img2 : "images/new/ridgehat/ridgehat3.png",
 Img2Alt : "",
 Img3 : "images/new/ridgehat/ridgehat4.png",
 Img3Alt : "",
 Img4 : "images/new/ridgehat/ridgehat5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "acc",
 price : 50,
},
{
 name : "Tab parka",
 ImgLink : "images/new/waistcoat/waistcoat.png",
 ImgAlt : "",
 description : "tab parka / reflector heather x COOL DOTS® ",
 description2 : "material has vents, and the functional material “COOL DOTS® (Cooldots)” with excellent breathability and water repellency is combined with a reflector print on the entire surface developed independently A pullover parka for switching between different materials that uses water-absorbing quick-drying material 'reflector heather'.",
 material : "Outer material: [Knit part] Heather knit x Reflective print (100% polyester) [Fabric part] COOL DOTS® x print (100% polyester)  ",
 measurements : "SMALL / Length: 67.5 cm Width: 67 cm Length: 84 cm MEDIUM / Length: 69.5 cm Width: 69 cm Length : 86.5 cm LARGE / Length: 71.5 cm Width: 71 cm Length: 89 cm EXTRA LARGE / Length: 73.5 cm Width: 73 cm Length: 91.5 cm",
 productId : "tabParka",
 Img1 : "images/new/waistcoat/waistcoat2.png",
 Img1Alt : "",
 Img2 : "images/new/waistcoat/waistcoat3.png",
 Img2Alt : "",
 Img3 : "images/new/waistcoat/waistcoat4.png",
 Img3Alt : "",
 Img4 : "images/new/waistcoat/waistcoat5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "outer",
 price : 80,
},
{
 name : "Windbreaker",
 ImgLink : "images/new/windbreakerhoodie/windbreakerhoodie.png",
 ImgAlt : "",
 description : "tab parka / reflector heather x COOL DOTS® ",
 description2 : "material has vents, and the functional material “COOL DOTS® (Cooldots)” with excellent breathability and water repellency is combined with a reflector print on the entire surface developed independently A pullover parka for switching between different materials that uses water-absorbing quick-drying material 'reflector heather'.",
 material : "Outer material: [Knit part] Heather knit x Reflective print (100% polyester) [Fabric part] COOL DOTS® x print (100% polyester)  ",
 measurements : "SMALL / Length: 67.5 cm Width: 67 cm Length: 84 cm MEDIUM / Length: 69.5 cm Width: 69 cm Length : 86.5 cm LARGE / Length: 71.5 cm Width: 71 cm Length: 89 cm EXTRA LARGE / Length: 73.5 cm Width: 73 cm Length: 91.5 cm",
 productId : "notchVest",
 Img1 : "images/new/windbreakerhoodie/windbreakerhoodie2.png",
 Img1Alt : "",
 Img2 : "images/new/windbreakerhoodie/windbreakerhoodie3.png",
 Img2Alt : "",
 Img3 : "images/new/windbreakerhoodie/windbreakerhoodie4.png",
 Img3Alt : "",
 Img4 : "images/new/windbreakerhoodie/windbreakerhoodie5.png",
 Img4Alt : "",
 sale : false,
 new : true,
 category : "outer",
 price : 180,
},
{
 name : "Dome coat",
 ImgLink : "images/sale/talljacket/talljacket.png",
 ImgAlt : "",
 description : "Super lightweight coat using dome coat / EPIC super water repellent material 'EPIC (Epic)'. ",
 description2 : "-A unique silhouette with a dome shaped hood and a voluminous silhouette that is supposed to be worn from above while carrying a backpack . ・ We place reflector print everywhere and secure visibility from all directions when walking at night. ・ It can be carried compactly if it is stored in the attached pouch. 　In addition, in order to prevent the loss of the attached pouch, the 　pocket inside the pocket for carrying the pouch portable is also equipped. -The hood is a drawcord specification. -The functional fiber 'Thunderon® (Saunderon)' with very high conductivity and corona discharge property is 　sewn in the inner stitch, and the generation of static electricity caused by friction is suppressed. -The front uses a snap button to improve lightness and storability. ",
 material : "Outer material: EPIC NY 20d 2-way stretch ripstop (100% nylon) ",
 measurements : "EXTRA SMALL / Length: 83 cm Width: 65 cm Length: 84.5 cm SMALL / Length: 85 cm Width: 67 cm Length: 87 cm MEDIUM / Length: 87 cm Width: 69 cm Length : 89.5cm LARGE / Length: 89cm Width : 71cm Length: 92cm EXTRA LARGE / Length: 91cm Width: 73cm Length: 94.5cm ",
 productId : "domeCoat",
 Img1 : "images/sale/talljacket/talljacket5.png",
 Img1Alt : "",
 Img2 : "images/sale/talljacket/talljacket2.png",
 Img2Alt : "",
 Img3 : "images/sale/talljacket/talljacket3.png",
 Img3Alt : "",
 Img4 : "images/sale/talljacket/talljacket4.png",
 Img4Alt : "",
 sale : true,
 new : false,
 category : "outer",
 price : 100,
},
{
 name : "Zak pack",
 ImgLink : "images/general/backpack/backpack0.png",
 ImgAlt : "",
 description : "lightweight backpack with a pocket design of zak coat (Zac coat). ",
 description2 : "・ We are divided into six parts and can arrange belongings to use. ・ The body part is the size that can accommodate A4 size PC. ・ Superior storage capacity and functionality at the time of action. ・ Direct access to the inside of the body is possible from the side zipper. ",
 material : "Outer material: Polyester 90% Polyurethane 10% ",
 measurements : "SIZE / H43: cm W: 32 cm",
 productId : "zakPak",
 Img1 : "images/general/backpack/backpack2.png",
 Img1Alt : "",
 Img2 : "images/general/backpack/backpack3.png",
 Img2Alt : "",
 Img3 : "images/general/backpack/backpack4.png",
 Img3Alt : "",
 Img4 : "images/general/backpack/backpack5.png",
 Img4Alt : "",
 sale : false,
 new : false,
 category : "acc",
 price : 20,
},
{
 name : "Zakoche",
 ImgLink : "images/general/medbag/medbag.png",
 ImgAlt : "",
 description : "lightweight medbag with a pocket design of zak coat (Zac coat). ",
 description2 : "・ We are divided into six parts and can arrange belongings to use. ・ The body part is the size that can accommodate A4 size PC. ・ Superior storage capacity and functionality at the time of action. ・ Direct access to the inside of the body is possible from the side zipper. ",
 material : "Outer material: Polyester 90% Polyurethane 10% ",
 measurements : "SIZE / H43: cm W: 32 cm",
 productId : "zakocheBag",
 Img1 : "images/general/medbag/medbag2.png",
 Img1Alt : "",
 Img2 : "images/general/medbag/medbag3.png",
 Img2Alt : "",
 Img3 : "images/general/medbag/medbag4.png",
 Img3Alt : "",
 Img4 : "images/general/medbag/medbag5.png",
 Img4Alt : "",
 sale : false,
 new : false,
 category : "acc",
 price : 40,
},
{
 name : "Crank Poach",
 ImgLink : "images/general/lilbag/lilbag1.png",
 ImgAlt : "",
 description : "A small pouch that uses a lightweight, durable, water-repellent stretch material 'karu stretch (cal stretch)' with a texture that has been uniquely developed. ",
 description2 : "-A shoulder strap made of a reflector material ensures nighttime visibility. ・ We are divided into two parts of large and small and assume carrying such as valuables. ",
 material : "Outer material: Nylon Taslan 2-way stretch taffeta (nylon 91%, polyurethane 9%) ",
 measurements : "SIZE / H: 17 cm W: 13 cm",
 productId : "crankPouch",
 Img1 : "images/general/lilbag/lilbag2.png",
 Img1Alt : "",
 Img2 : "images/general/lilbag/lilbag1.png",
 Img2Alt : "",
 Img3 : "images/general/lilbag/lilbag2.png",
 Img3Alt : "",
 Img4 : "images/general/lilbag/lilbag1.png",
 Img4Alt : "",
 sale : false,
 new : false,
 category : "acc",
 price : 30,
},

]